[package]
name = "debug_iterator"
version = "0.1.0"
authors = ["museun <museun@outlook.com>"]
edition = "2018"

[dependencies]
log = { version = "0.4.7", optional = true }

[features]
default = []
serialize = ["serde"]
logging = ["log"]
